service: sqs-resources
frameworkVersion: '3'

custom:
  stage: ${opt:stage, self:provider.stage}
  queue01Name: tp-lend-mca-trigger-merchant-txn-collection
  dlQueueName: my-dlq-sqs

provider:
  name: aws
  stage: dev

resources:
  Resources:
    Test01SQSQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.queue01Name}
    dlQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: 
          Fn::Sub: ${self:custom.dlQueueName}
  Outputs:
    test01SQSQueue:
      Value: ${self:custom.queue01Name}
    test01SQSQueueArn:
      Value: !GetAtt Test01SQSQueue.Arn
    dlQueue:
      Value: ${self:custom.dlQueueName}
    dlQueueArn:
      Value: !GetAtt dlQueue.Arn