service: ${self:custom.servicePrefix}-private-rest-api-gateway
frameworkVersion: "3"

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  servicePrefix: thlinh

provider:
  stage: local
  region: ap-southeast-1
  name: aws

#############
# RESOURCES #
#############
resources:
  Parameters:
    vpcId:
      Type: String
      Default: ${param:vpcId}
    privateSubnetOneId:
      Type: String
      Default: ${param:privateSubnetOneId}
    privateSubnetTwoId:
      Type: String
      Default: ${param:privateSubnetTwoId}
    privateSubnetThreeId:
      Type: String
      Default: ${param:privateSubnetThreeId}
    vpcLink:
      Type: String
      Default: ${param:vpcLinkId}
    managedSgTxToolingBaseSecurityGroupId:
      Type: String
      Default: ${param:managedSgTxToolingBaseSecurityGroupId}
    managedSgTxInfrastructureBaseSecurityGroupId:
      Type: String
      Default: ${param:managedSgTxInfrastructureBaseSecurityGroupId}
  Resources:
    GWVPCEndpoint:
      Type: AWS::EC2::VPCEndpoint
      Properties:
        ServiceName: com.amazonaws.${self:provider.region}.execute-api
        VpcId: !Ref vpcId
        VpcEndpointType: Interface
        PrivateDnsEnabled: true
        SubnetIds:
          - !Ref privateSubnetOneId
          - !Ref privateSubnetTwoId
          - !Ref privateSubnetThreeId
        SecurityGroupIds:
          - !Ref managedSgTxToolingBaseSecurityGroupId
          - !Ref managedSgTxInfrastructureBaseSecurityGroupId

    RestApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.servicePrefix}-private-rest-api-gateway
        Description: Private - Rest Api Gateway
        EndpointConfiguration:
          Types:
            - PRIVATE
        Policy:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: execute-api:Invoke
              Resource:
                - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*
            - Effect: Deny
              Principal: "*"
              Action: execute-api:Invoke
              Resource:
                - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*
              Condition:
                StringNotEquals:
                  aws:SourceVpce:
                    - !Ref GWVPCEndpoint

  Outputs:
    RestApiId:
      Description: Rest Api Id
      Value: !Ref RestApiGateway
    RestApiRootResourceId:
      Description: Rest Api Root Resource Id
      Value: !GetAtt RestApiGateway.RootResourceId
    APIURL:
      Description: Invoke URL
      Value: !Sub https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/
