service: ${self:custom.servicePrefix}-tgw
frameworkVersion: '3'

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  servicePrefix: thlinh

provider:
  stage: local
  region: us-west-2
  name: aws

#############
# RESOURCES #
#############
resources:
  Parameters:
    Vpc:
      Type: String
      Default: ${param:vpcId}
    PrivateSubnetOne:
      Type: String
      Default: ${param:privateSubnetOneId}
    PrivateSubnetTwo:
      Type: String
      Default: ${param:privateSubnetTwoId}
    PrivateSubnetThree:
      Type: String
      Default: ${param:privateSubnetThreeId}
    PrivateRouteTableId:
      Type: String
      Default: ${param:privateRouteTableId}
    TargetTGWVPCCidr:
      Type: String
      Default: ${param:targetTgwVpcCidr}
  Resources:
    TGW:
      Type: AWS::EC2::TransitGateway
      Properties:
        AutoAcceptSharedAttachments: enable
        DefaultRouteTableAssociation: enable
        DefaultRouteTablePropagation: enable
        VpnEcmpSupport: disable
        DnsSupport: enable
        MulticastSupport: disable
        Tags:
          - Key: Name
            Value: !Sub ${AWS::StackName}
    TGWVPCattachment:
      Type: AWS::EC2::TransitGatewayAttachment
      Properties:
        Options:
          DnsSupport: enable
        SubnetIds:
          - !Ref PrivateSubnetOne
          - !Ref PrivateSubnetTwo
          - !Ref PrivateSubnetThree
        TransitGatewayId: !Ref TGW
        VpcId: !Ref Vpc
        Tags:
          - Key: Name
            Value: !Sub ${AWS::StackName}-Attachment
    PrivateRouteTGW:
      Type: 'AWS::EC2::Route'
      DependsOn: TGWVPCattachment
      Properties:
        RouteTableId: !Ref PrivateRouteTableId
        DestinationCidrBlock: !Ref TargetTGWVPCCidr
        # Unsupported PrefixList in AWS::EC2::Route at this time
        # DestinationPrefixListId: !Ref VPCPrefixList
        TransitGatewayId: !Ref TGW
  Outputs:
    tgwId:
      Description: Transit gateway id
      Value: !Ref TGW
