service: s3-resources
frameworkVersion: '3'

custom:
  stage: ${opt:stage, self:provider.stage}
  bucketName: my-s3-test-bucket.linhth.com

provider:
  name: aws
  stage: dev

resources:
  Resources:
    testS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        LifecycleConfiguration:
          Rules:
            - Id: GlacierRule
              Prefix: data
              Status: Enabled
              Transitions:
                - TransitionInDays: 7
                  StorageClass: GLACIER
                - TransitionInDays: 365
                  StorageClass: DEEP_ARCHIVE


  Outputs:
    s3BucketArn:
      Value: !GetAtt testS3Bucket.Arn
    s3BucketName:
      Value: ${self:custom.bucketName}