services:
  vpc:
    path: account-A/vpc
    params:
      vpcCidr: '10.90.64.0/19'
      privateSubnetOneCidr: '10.90.72.0/22'
      privateSubnetTwoCidr: '10.90.76.0/22'
      privateSubnetThreeCidr: '10.90.80.0/22'
      publicSubnetOneCidr: '10.90.64.0/24'
      publicSubnetTwoCidr: '10.90.65.0/24'
      publicSubnetThreeCidr: '10.90.66.0/24'

  vpc-ec2:
    path: account-A/test-ec2
    params:
      vpcId: ${vpc.vpcId}
      privateSubnetOneId: ${vpc.privateSubnetOneId}
      privateSubnetTwoId: ${vpc.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc.privateSubnetThreeId}
      managedSgTxToolingBaseSecurityGroup: ${vpc.managedSgTxToolingBaseSecurityGroup}
      infrastructureBaseSecurityGroupId: ${vpc.infrastructureBaseSecurityGroupId}

  vpc-tgw:
    path: account-A/transit-gateway
    params:
      vpcId: ${vpc.vpcId}
      privateSubnetOneId: ${vpc.privateSubnetOneId}
      privateSubnetTwoId: ${vpc.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc.privateSubnetThreeId}
      tgwId: ${vpc-x-tgw.tgwId}
      privateRouteTableId: ${vpc.privateRouteTableId}
      targetTgwVpcCidr: '10.220.64.0/18'

  vpc-link:
    path: account-A/vpclink
    params:
      vpcId: ${vpc.vpcId}
      privateSubnetOneId: ${vpc.privateSubnetOneId}
      privateSubnetTwoId: ${vpc.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc.privateSubnetThreeId}
      targetVPCEndpointSubnetOneAddress: '10.220.82.73'
      targetVPCEndpointSubnetTwoAddress: '10.220.66.31'
      targetVPCEndpointSubnetThreeAddress: '10.220.74.210'

  regional-rest-gw:
    path: account-A/regional-rest-gw

  # VPC-X

  vpc-x:
    path: account-X/vpc-x
    params:
      vpcCidr: '10.220.64.0/18'
      privateSubnetOneCidr: '10.220.64.0/21'
      privateSubnetTwoCidr: '10.220.72.0/21'
      privateSubnetThreeCidr: '10.220.80.0/21'
      inboundVpcCidr: '10.90.64.0/19'

  vpc-x-ingress-rest-gw:
    path: account-X/x-private-gw
    params:
      vpcName: ${vpc-x.vpcName}
      vpcEndpointId: ${vpc-x.vpcEndpointId}
      vpcId: ${vpc-x.vpcId}
      privateSubnetOneId: ${vpc-x.privateSubnetOneId}
      privateSubnetTwoId: ${vpc-x.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc-x.privateSubnetThreeId}
      managedSgTxToolingBaseSecurityGroup: ${vpc-x.managedSgTxToolingBaseSecurityGroup}
      infrastructureBaseSecurityGroupId: ${vpc-x.infrastructureBaseSecurityGroupId}

  vpc-x-ec2:
    path: account-X/test-ec2
    params:
      vpcId: ${vpc-x.vpcId}
      privateSubnetOneId: ${vpc-x.privateSubnetOneId}
      privateSubnetTwoId: ${vpc-x.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc-x.privateSubnetThreeId}
      managedSgTxToolingBaseSecurityGroup: ${vpc-x.managedSgTxToolingBaseSecurityGroup}
      infrastructureBaseSecurityGroupId: ${vpc-x.infrastructureBaseSecurityGroupId}

  vpc-x-tgw:
    path: account-X/transit-gateway
    params:
      vpcId: ${vpc-x.vpcId}
      privateSubnetOneId: ${vpc-x.privateSubnetOneId}
      privateSubnetTwoId: ${vpc-x.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc-x.privateSubnetThreeId}
      privateRouteTableId: ${vpc-x.privateRouteTableId}
      targetTgwVpcCidr: '10.90.64.0/19'