services:
  vpc:
    path: account-A/vpc

  vpc-x:
    path: account-X/vpc-x

  vpc-x-ingress-rest-gw:
    path: account-X/x-private-gw
    params:
      vpcName: ${vpc-x.vpcName}
      vpcEndpointId: ${vpc-x.vpcEndpointId}
      vpcId: ${vpc-x.vpcId}
      privateSubnetOneId: ${vpc-x.privateSubnetOneId}
      privateSubnetTwoId: ${vpc-x.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc-x.privateSubnetThreeId}
      managedSgTxToolingBaseSecurityGroup: ${vpc-x.managedSgTxToolingBaseSecurityGroup}
      infrastructureBaseSecurityGroupId: ${vpc-x.infrastructureBaseSecurityGroupId}

  vpc-x-ec2:
    path: account-X/test-ec2
    params:
      vpcId: ${vpc-x.vpcId}
      privateSubnetOneId: ${vpc-x.privateSubnetOneId}
      privateSubnetTwoId: ${vpc-x.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc-x.privateSubnetThreeId}
      managedSgTxToolingBaseSecurityGroup: ${vpc-x.managedSgTxToolingBaseSecurityGroup}
      infrastructureBaseSecurityGroupId: ${vpc-x.infrastructureBaseSecurityGroupId}