service: ${self:custom.servicePrefix}-private-rest-api-gateway
frameworkVersion: "3"

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  servicePrefix: thlinh

provider:
  stage: local
  region: ap-southeast-1
  name: aws

#############
# RESOURCES #
#############
resources:
  Parameters:
    vpcLink:
      Type: String
      Default: ${param:vpcLinkId}
    privateNlbDnsName:
      Type: String
      Default: ${param:privateNlbDnsName}
  Resources:
    RestApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: ${self:custom.servicePrefix}-private-rest-api-gateway
        Description: Private - Rest Api Gateway
        EndpointConfiguration:
          Types:
            - PRIVATE

    ProxyResource:
      Type: AWS::ApiGateway::Resource
      Properties:
        ParentId: !GetAtt RestApiGateway.RootResourceId
        PathPart: "{proxy+}"
        RestApiId: !Ref RestApiGateway

    ProxyMethod:
      Type: AWS::ApiGateway::Method
      Properties:
        ResourceId: !Ref ProxyResource
        RestApiId: !Ref RestApiGateway
        HttpMethod: ANY
        OperationName: "ProxyAllRequests"
        ApiKeyRequired: false
        AuthorizationType: NONE
        RequestParameters:
          method.request.path.proxy: true
        Integration:
          RequestParameters:
            integration.request.path.proxy: method.request.path.proxy
          Type: HTTP_PROXY
          IntegrationHttpMethod: ANY
          Uri: !Sub "http://${privateNlbDnsName}/{proxy}"
          ConnectionType: VPC_LINK
          ConnectionId: !Ref vpcLink

  Outputs:
    APIURL:
      Description: Invoke URL
      Value: !Sub https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/
