service: ${self:custom.servicePrefix}-vpclink
frameworkVersion: '3'

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  servicePrefix: thlinh

provider:
  stage: local
  region: us-east-1
  name: aws

#############
# RESOURCES #
#############
resources:
  Parameters:
    Vpc:
      Type: String
      Default: ${param:vpcId}
    PrivateSubnetOne:
      Type: String
      Default: ${param:privateSubnetOneId}
    PrivateSubnetTwo:
      Type: String
      Default: ${param:privateSubnetTwoId}
    PrivateSubnetThree:
      Type: String
      Default: ${param:privateSubnetThreeId}
    TargetVPCEndpointSubnetOneAddress:
      Type: String
      Default: ${param:targetVPCEndpointSubnetOneAddress}
    TargetVPCEndpointSubnetTwoAddress:
      Type: String
      Default: ${param:targetVPCEndpointSubnetTwoAddress}
    TargetVPCEndpointSubnetThreeAddress:
      Type: String
      Default: ${param:targetVPCEndpointSubnetThreeAddress}
  Resources:
    privateNlb:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Name: ${self:custom.servicePrefix}-private-nlb
        Type: network
        Subnets:
          - !Ref PrivateSubnetOne
          - !Ref PrivateSubnetTwo
          - !Ref PrivateSubnetThree

    # Create Target Group from Nlb To Alb
    PrivateNlbToVpcEndpoints:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        Name: vpc-a-nlb-to-vpcx-endpoint
        Protocol: TCP
        Port: 443
        VpcId: !Ref Vpc
        TargetType: ip
        Targets:
          - Id: !Ref TargetVPCEndpointSubnetOneAddress
            Port: 443
          - Id: !Ref TargetVPCEndpointSubnetTwoAddress
            Port: 443
          - Id: !Ref TargetVPCEndpointSubnetThreeAddress
            Port: 443
        HealthCheckEnabled: true
        HealthCheckProtocol: TCP
        HealthCheckPort: traffic-port
#        HealthCheckPath: "/health"
        HealthCheckIntervalSeconds: 30
        HealthCheckTimeoutSeconds: 5
        HealthyThresholdCount: 3
        UnhealthyThresholdCount: 5
        TargetGroupAttributes:
          - Key: deregistration_delay.timeout_seconds
            Value: 300
#  Outputs:
#    tgwId:
#      Description: Transit gateway id
#      Value: !Ref TGW
