service: saas-gw-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  apiGateway:
    apiKeys:
      - name: ${self:service}-${self:provider.stage}-apikey
        enabled: true
  logs:
    restApi:
      accessLogging: true
      executionLogging: true
      level: INFO
  environment:
    STAGE: ${self:provider.stage}

functions:
  # Lambda Authorizer function
  authorizer:
    handler: src/handlers/authorizer.handler
    description: Lambda authorizer that adds partnerId to the request context

  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          path: api/abc/hello
          method: post
          private: true  # Requires API key
          cors: true
          authorizer: 
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.x-api-key
      - http:
          path: api/tymebank/hello
          method: post
          private: true
          cors: true
          authorizer: 
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.x-api-key
      - http:
          path: api/sanlam/hello
          method: post
          private: true
          cors: true
          authorizer: 
            name: authorizer
            resultTtlInSeconds: 0
            type: request
            identitySource: method.request.header.x-api-key

resources:
  Description: CloudFront distribution with API Gateway origin
  Resources:
    # CloudFront Function for path rewriting
    CloudFrontPathRewriteFunction:
      Type: AWS::CloudFront::Function
      Properties:
        Name: ${self:service}-${self:provider.stage}-path-rewrite
        AutoPublish: true
        FunctionConfig:
          Comment: "CloudFront Function to rewrite partner-specific paths to standard API paths"
          Runtime: cloudfront-js-1.0
        FunctionCode: 
          Fn::Join:
            - ""
            - - |
                function handler(event) {
                  var request = event.request;
                  var uri = request.uri;
                  
                  // Check if the path starts with any of the partner-specific paths
                  if (uri.startsWith('/api/tymebank/hello') || uri.startsWith('/api/sanlam/hello')) {
                    // Store the original URI for reference
                    var originalUri = uri;
                    
                    // Rewrite to the generic path
                    request.uri = '/api/abc/hello';
                    
                    // Log the rewrite (visible in CloudWatch Logs if you enable logging)
                    console.log('Path rewritten from ' + originalUri + ' to ' + request.uri);
                  }
                  
                  return request;
                }

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Comment: "CloudFront for API Gateway"
          Origins:
            - Id: ApiGatewayOrigin
              DomainName: 
                Fn::Join:
                  - ""
                  - - Ref: "ApiGatewayRestApi"
                    - ".execute-api.${self:provider.region}.amazonaws.com"
              OriginPath: "/${self:provider.stage}"
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
                OriginSSLProtocols:
                  - TLSv1.2
          # Default behavior for any unmatched paths
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            TargetOriginId: ApiGatewayOrigin
            ForwardedValues:
              QueryString: true
              Headers:
                - x-api-key
                - Authorization
                - Content-Type
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
          # Partner-specific cache behaviors
          CacheBehaviors:
            # Tymebank path pattern
            - PathPattern: "api/tymebank/*"
              TargetOriginId: ApiGatewayOrigin
              AllowedMethods:
                - DELETE
                - GET
                - HEAD
                - OPTIONS
                - PATCH
                - POST
                - PUT
              CachedMethods:
                - GET
                - HEAD
                - OPTIONS
              ForwardedValues:
                QueryString: true
                Headers:
                  - x-api-key
                  - Authorization
                  - Content-Type
                Cookies:
                  Forward: none
              ViewerProtocolPolicy: redirect-to-https
              MinTTL: 0
              DefaultTTL: 0
              MaxTTL: 0
              FunctionAssociations:
                - EventType: viewer-request
                  FunctionARN: !GetAtt CloudFrontPathRewriteFunction.FunctionARN
            # Sanlam path pattern  
            - PathPattern: "api/sanlam/*"
              TargetOriginId: ApiGatewayOrigin
              AllowedMethods:
                - DELETE
                - GET
                - HEAD
                - OPTIONS
                - PATCH
                - POST
                - PUT
              CachedMethods:
                - GET
                - HEAD
                - OPTIONS
              ForwardedValues:
                QueryString: true
                Headers:
                  - x-api-key
                  - Authorization
                  - Content-Type
                Cookies:
                  Forward: none
              ViewerProtocolPolicy: redirect-to-https
              MinTTL: 0
              DefaultTTL: 0
              MaxTTL: 0
              FunctionAssociations:
                - EventType: viewer-request
                  FunctionARN: !GetAtt CloudFrontPathRewriteFunction.FunctionARN
          PriceClass: PriceClass_100
          ViewerCertificate:
            CloudFrontDefaultCertificate: true

  Outputs:
    CloudFrontDomainName:
      Value:
        Fn::GetAtt:
          - CloudFrontDistribution
          - DomainName
      Description: Domain name of CloudFront distribution
    CloudFrontFunctionARN:
      Value:
        Fn::GetAtt:
          - CloudFrontPathRewriteFunction
          - FunctionARN
      Description: ARN of the CloudFront path rewrite function

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'
    - '!.pytest_cache/**'
    - '!tests/**' 