service: saas-gw-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  apiGateway:
    apiKeys:
      - name: ${self:service}-${self:provider.stage}-apikey
        enabled: true
  environment:
    STAGE: ${self:provider.stage}

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - http:
          path: api/abc/hello
          method: post
          private: true  # Requires API key
          cors: true

resources:
  Description: CloudFront distribution with API Gateway origin
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Comment: "CloudFront for API Gateway"
          Origins:
            - Id: ApiGatewayOrigin
              DomainName: 
                Fn::Join:
                  - ""
                  - - Ref: "ApiGatewayRestApi"
                    - ".execute-api.${self:provider.region}.amazonaws.com"
              OriginPath: "/${self:provider.stage}"
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
                OriginSSLProtocols:
                  - TLSv1.2
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            CachedMethods:
              - GET
              - HEAD
              - OPTIONS
            TargetOriginId: ApiGatewayOrigin
            ForwardedValues:
              QueryString: true
              Headers:
                - x-api-key
                - Authorization
                - Content-Type
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
            MinTTL: 0
            DefaultTTL: 0
            MaxTTL: 0
          PriceClass: PriceClass_100
          ViewerCertificate:
            CloudFrontDefaultCertificate: true

  Outputs:
    CloudFrontDomainName:
      Value:
        Fn::GetAtt:
          - CloudFrontDistribution
          - DomainName
      Description: Domain name of CloudFront distribution

plugins:
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'
    - '!.pytest_cache/**'
    - '!tests/**' 