service: ${self:custom.servicePrefix}-service
frameworkVersion: '4'

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  servicePrefix: arb-poc
  pythonRequirements:
    usePoetry: true
    slim: true
    layer: true
    noDeploy:
      - pytest

provider:
  name: aws
  runtime: python3.12
  region: ${opt:region, 'eu-central-1'}
  environment:
    REGION: ${opt:region, 'eu-central-1'}
    ORDER_TABLE: 'order_table'
  stage: local

functions:
  poc-receiver:
    handler: src.index.handle
    events:
      - httpApi:
          path: /ecommerce/{proxy+}
          method: '*'
    layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python312-x86_64:2
      - Ref: PythonRequirementsLambdaLayer
    package:
      include:
        - src/**

plugins:
  - serverless-offline
  - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!htmlcov'
    - '!venv'
    - '!node_modules'
    - '!.serverless/requirements'
    - "!${opt:package, '.serverless'}"
    - '!configs'
    - '!*.yml*'
    - '!*.json'
    - '!*.sh'
    - 'lib'
    - '*.py'
  excludeDevDependencies: false