service: ${self:custom.servicePrefix}-order-service
frameworkVersion: '4'

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  servicePrefix: arb-poc
  pythonRequirements:
    usePoetry: true
    slim: true
    layer: true
    noDeploy:
      - pytest
  orderTable: ${self:custom.servicePrefix}-order-table

provider:
  name: aws
  runtime: python3.12
  region: ${opt:region, 'eu-central-1'}
  environment:
    REGION: ${opt:region, 'eu-central-1'}
    ORDER_TABLE: ${self:custom.orderTable}
    RUNNING_STAGE: ${self:custom.stage}
  stage: local

functions:
  order-apis:
    name: ${self:custom.servicePrefix}-order-svc
    handler: src.index.handle
    timeout: 29
    events:
      - httpApi:
          path: /ecommerce/{proxy+}
          method: '*'
    iamRoleStatementsName: ${self:custom.servicePrefix}-order-svc-${self:custom.stage}-${self:custom.region}-custom-lambdaRole
    iamRoleStatements:
      - Effect: Allow
        Sid: DynamoDBTableAccess
        Action:
          - dynamodb:Get*
          - dynamodb:Query
          - dynamodb:PutItem
          - dynamodb:Update*
          - dynamodb:BatchWriteItem
          - dynamodb:BatchGet*
        Resource:
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.orderTable}
          - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:custom.orderTable}/index/*
    layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python312-x86_64:2
      - Ref: PythonRequirementsLambdaLayer

  validate-orders:
    name: ${self:custom.servicePrefix}-validate-order-processor
    handler: src.processor.validate_order_processor.handle
    events:
      - sqs:
          arn: arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:${self:custom.servicePrefix}-order-placed-queue
    layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python312-x86_64:2
      - Ref: PythonRequirementsLambdaLayer

resources:
  Resources:
    HttpUrlSSMParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:service}/${self:custom.stage}/api-gateway-url
        Type: String
        Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/
        Tags:
          Environment: ${self:custom.stage}
          Team: "9999"

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-iam-roles-per-function
  - serverless-cloudformation-sub-variables

package:
  individually: true
  patterns:
    - '!htmlcov'
    - '!venv'
    - '!node_modules'
    - '!.serverless/requirements'
    - "!${opt:package, '.serverless'}"
    - '!.idea'
    - '!.pytest_cache'
    - '!configs'
    - '!*.yml*'
    - '!*.json'
    - '!*.sh'
    - 'lib'
    - '*.py'
  include:
    - src/**
  excludeDevDependencies: false