service: ${self:custom.servicePrefix}-private-alb
frameworkVersion: '3'

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  servicePrefix: thlinh

provider:
  stage: local
  region: us-east-1
  name: aws


#############
# RESOURCES #
#############
resources:
  Parameters:
    Vpc:
      Type: String
      Default: ${param:vpcId}
    PrivateSubnetOne:
      Type: String
      Default: ${param:privateSubnetOneId}
    PrivateSubnetTwo:
      Type: String
      Default: ${param:privateSubnetTwoId}
    PrivateSubnetThree:
      Type: String
      Default: ${param:privateSubnetThreeId}

  Resources:
# Private internal load balancer, hosted in private subnets that is accessible
# only from VPClink. Rules are added to this security group when VPC Link Security has been created
    PrivateLoadBalancerSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Access to the public facing load balancer
        GroupName: ALB Security Group
        VpcId: !Ref Vpc

    PrivateLoadBalancer:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        Name: private-alb
        Scheme: internal
        LoadBalancerAttributes:
          - Key: idle_timeout.timeout_seconds
            Value: '30'
        Type: application
        Subnets:
          -  !Ref PrivateSubnetOne
          -  !Ref PrivateSubnetTwo
          -  !Ref PrivateSubnetThree
        IpAddressType: ipv4
        SecurityGroups:
          - !Ref PrivateLoadBalancerSecurityGroup

    ALBTargetGroupPrivate:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        TargetType: ip
        HealthCheckIntervalSeconds: 10
        HealthCheckProtocol: HTTP
        HealthCheckTimeoutSeconds: 5
        HealthyThresholdCount: 5
        UnhealthyThresholdCount: 3
        Matcher:
          HttpCode: '200-299'
        Port: 80
        Protocol: HTTP
        VpcId: !Ref Vpc
        TargetGroupAttributes:
          - Key: deregistration_delay.timeout_seconds
            Value: '5'
          - Key: slow_start.duration_seconds
            Value: '60'

    PrivateLoadBalancerListener:
      Type: AWS::ElasticLoadBalancingV2::Listener
      Properties:
        DefaultActions:
          - TargetGroupArn: !Ref ALBTargetGroupPrivate
            Type: forward
        LoadBalancerArn: !Ref PrivateLoadBalancer
        Port: 80
        Protocol: HTTP
  Outputs:
    albListenerArn:
      Value: !Ref PrivateLoadBalancerListener
    privateLoadBalancerSecurityGroup:
      Value: !Ref PrivateLoadBalancerSecurityGroup