services:
  s3:
    path: resources/s3

  firehose:
    path: resources/firehose
    params:
      testS3BucketArn: ${s3.testS3BucketArn}
      bucketName: ${s3.bucketName}
    dependsOn:
      - s3

  dynamodb:
    path: resources/dynamodb

  sqs:
    path: resources/sqs
    params:
      dlqSQSName:  my-dlq-sqs

  capturer:
    path: stream-capturer
    params:
      bucketName: ${s3.bucketName}
      dlqName: my-dlq-sqs
    dependsOn:
      - dynamodb
      - firehose

  lambdas:
    path: lambda-multiple-funcs
    dependsOn:
      - dynamodb
      - firehose
      - sqs