services:
  s3:
    path: resources/s3

  firehose:
    path: resources/firehose
    params:
      s3BucketArn: ${s3.s3BucketArn}
      s3BucketName: ${s3.s3BucketName}
    dependsOn:
      - s3

  dynamodb:
    path: resources/dynamodb

  sqs:
    path: resources/sqs

  capturer:
    path: stream-capturer
    params:
      bucketName: ${s3.s3BucketName}
      dlqName: my-dlq-sqs
    dependsOn:
      - dynamodb
      - firehose

  lambdas:
    path: lambda-multiple-funcs
    dependsOn:
      - dynamodb
      - firehose
      - sqs