services:
  vpc:
    path: resources/vpc
  alb:
    path: resources/alb
    params:
      vpcId: ${vpc.vpcId}
      privateSubnetOneId: ${vpc.privateSubnetOneId}
      privateSubnetTwoId: ${vpc.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc.privateSubnetThreeId}

  test-alb-fn:
    path: test-alb-fn
    params:
      albListenerArn: ${alb.albListenerArn}