services:
  vpc:
    path: resources/vpc

  alb:
    path: resources/alb
    params:
      vpcId: ${vpc.vpcId}
      privateSubnetOneId: ${vpc.privateSubnetOneId}
      privateSubnetTwoId: ${vpc.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc.privateSubnetThreeId}

  public-alb:
    path: resources/public-alb
    params:
      vpcId: ${vpc.vpcId}
      publicSubnetOneId: ${vpc.publicSubnetOneId}
      publicSubnetTwoId: ${vpc.publicSubnetTwoId}
      publicSubnetThreeId: ${vpc.publicSubnetThreeId}

  test-alb-fn:
    path: test-alb-fn
    params:
      albListenerArn: ${public-alb.albListenerArn}
      privateSubnetOneId: ${vpc.privateSubnetOneId}
      privateSubnetTwoId: ${vpc.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc.privateSubnetThreeId}
      privateLoadBalancerSecurityGroup: ${alb.privateLoadBalancerSecurityGroup}

  api-gateway:
    path: resources/api-gateway
    params:
      vpcId: ${vpc.vpcId}
      privateSubnetOneId: ${vpc.privateSubnetOneId}
      privateSubnetTwoId: ${vpc.privateSubnetTwoId}
      privateSubnetThreeId: ${vpc.privateSubnetThreeId}
      albListenerArn: ${alb.albListenerArn}