service: ${self:custom.servicePrefix}-api-gateway
frameworkVersion: '3'

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  servicePrefix: thlinh

provider:
  stage: local
  region: us-east-1
  name: aws


#############
# RESOURCES #
#############
resources:
  Parameters:
    Vpc:
      Type: String
      Default: ${param:vpcId}
    PrivateSubnetOne:
      Type: String
      Default: ${param:privateSubnetOneId}
    PrivateSubnetTwo:
      Type: String
      Default: ${param:privateSubnetTwoId}
    PrivateSubnetThree:
      Type: String
      Default: ${param:privateSubnetThreeId}
    PrivateLoadBalancerListener:
      Type: String
      Default: ${param:albListenerArn}
  Resources:
    APIGWVPClinkSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        VpcId: !Ref Vpc
        GroupName: vpclink-security-group
        GroupDescription: APIGW vpclink security group
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0

    PrivateAPIGWvpcLink:
      Type: AWS::ApiGatewayV2::VpcLink
      Properties:
        Name: private-apigw-vpclink
        SecurityGroupIds:
          - !Ref APIGWVPClinkSG
        SubnetIds:
          - !Ref PrivateSubnetOne
          - !Ref PrivateSubnetTwo
          - !Ref PrivateSubnetThree

    HttpApiGateway:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: ${self:custom.servicePrefix}-api-gateway
        Description: Api Gateway for http
        ProtocolType: HTTP

    APIRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId: !Ref HttpApiGateway
        RouteKey: 'ANY /'
        Target: !Join
          - /
          - - integrations
            - !Ref APIAlbIntegration

    APIAlbIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId: !Ref HttpApiGateway
        Description: Private ALB Integration
        IntegrationType: HTTP_PROXY
        IntegrationMethod: ANY
        ConnectionType: VPC_LINK
        ConnectionId: !Ref PrivateAPIGWvpcLink
        IntegrationUri: !Ref PrivateLoadBalancerListener
        PayloadFormatVersion: '1.0'

    APIStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        StageName: $default
        AutoDeploy: true
        ApiId: !Ref HttpApiGateway

  Outputs:
    APIURL:
      Description: Invoke URL
      Value: !Sub https://${HttpApiGateway}.execute-api.${AWS::Region}.amazonaws.com/