service: ${self:custom.servicePrefix}-eventbridge-service
frameworkVersion: '4'

custom:
  stage: ${opt:stage, self:provider.stage}
  servicePrefix: arb-poc

provider:
  name: aws
  runtime: python3.12
  region: ${opt:region, 'eu-central-1'}
  stage: local

resources:
  Resources:
    CustomEventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:custom.servicePrefix}-event-bus
        Tags:
          - Key: Team
            Value: 9999
    CustomEventBusArnSSMParameter:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /arb/poc/${self:custom.stage}/eventbus/arn
        Type: String
        Value: !GetAtt CustomEventBus.Arn
        Tags:
          Environment: ${self:custom.stage}
          Team: "9999"

  Outputs:
    EventBusName:
      Value: !Ref CustomEventBus
    EventBusNameArn:
      Value: !GetAtt CustomEventBus.Arn